# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: chocolat lumière
            image:
        nav:
            - item_name: トップ
              item_url: '/'
            - item_name: 困った時は
              item_url: '#'
    footer:
        content:
            logo:
                text: chocolat lumière
                image:
            copyright: Copyright &copy; 2018. - chocolat lumière <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/chocolatlumiere'
            - network_name: instagram
              profile_url: 'https://instagram.com/chocolatlumiere'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
